name: chapters_db
description: Create For Chapters Database.
version: 0.2.0
repository: https://github.com/ThanCoder/chapters_db

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
